// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing/Desktop.tsx": () => import("../components/mockups/landing/Desktop.tsx"),
  "./components/mockups/landing/Mobile.tsx": () => import("../components/mockups/landing/Mobile.tsx")
};
